#cloud-config

users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLq+h1m2bQK9CnHoyHzQPr9KH3lDpErUe0tm+PlAOZWR+qnXf2yjvPigG7iDPwb4J/jkNGKKOG5JCB65kPprAOR+WmbA/FAmiGUNw/PiHXei7bYfrsyvN/SQUOjj8uDeORzScshCMYG3IECtQru4D9gNRXEOxgthvKx1UCWGwNnsByUleGK9Fg45Ambd0Bgs12TMNn9eQI/Gr81jhu8V7wdb0TIASGP2K1z2DZS1eogp0vtQnN9eck/4SjehO+slEt5nXvq9UNvh93TgPIqa6GbQLtKwaOPMxoGJTHEGrL5gnAI05mEv/FOCv5rR3k4mvatUM5dZLdMu2KJev9WapKwO6vEY4L5Rb4zyTYc5/wuPgl39WhKf97LtmTMTNAqgrUkFebrMmjuz7jHUibYscBb8TdLmxufaEoaGzoxvNc0d5fBOWcNetM1Iw4skkvI76m7tS2AW6FnwL9IpVZMI74MYlBwaqA6zoR/9cH8AxqBCNu7KV50+iGjTg96IMhgk0= appuser

write_files:
  - path: ./install_ruby.sh
    permissions: "0644"
    content: |
      #!/bin/bash
      sudo apt update
      sudo apt install -y ruby-full ruby-bundler build-essential mc nano
  - path: ./install_mongodb.sh
    permissions: "0644"
    content: |
      #!/bin/bash
      wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      sudo apt-get update
      sudo apt-get install -y mongodb-org
      sudo systemctl start mongod
      sudo systemctl enable mongod
  - path: ./deploy.sh
    permissions: "0644"
    content: |
      #!/bin/bash
      sudo install git
      git clone -b monolith https://github.com/express42/reddit.git
      cd reddit
      bundle install
      puma -d
  - path: ./startup.sh
    permissions: "0644"
    content: |
      #!/bin/bash
      ./install_ruby.sh && ./install_mongodb.sh && ./init_scripts/deploy.sh

runcmd:
  - ./startup.sh
